name: hs_workflow_intro_to_github_actions_1
on: [push]
jobs:
  show-secret-phrase:
    runs-on: ubuntu-latest
    steps:
      - name: Greetings
      - uses: actions/checkout@v3
        with:
         repository: abystoma/external-workflow
         ref: 3eb718710f20d7df6874acdc41e189a2ae4182f5
        run: echo "$(<greeting.txt)"
